# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: currency_tracker.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='currency_tracker.proto',
  package='currency_tracker',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16\x63urrency_tracker.proto\x12\x10\x63urrency_tracker\"\x07\n\x05\x45mpty\"\x1f\n\x0b\x43\x61ncelation\x12\x10\n\x08\x62\x61nkName\x18\x01 \x01(\t\"X\n\x0c\x43urrencyData\x12\x30\n\x08\x63urrency\x18\x01 \x01(\x0e\x32\x1e.currency_tracker.CurrencyName\x12\x16\n\x0e\x65xchange_ratio\x18\x02 \x01(\x01\"T\n\x0cSubscription\x12\x10\n\x08\x62\x61nkName\x18\x01 \x01(\t\x12\x32\n\ncurrencies\x18\x02 \x03(\x0e\x32\x1e.currency_tracker.CurrencyName*;\n\x0c\x43urrencyName\x12\x07\n\x03\x41UD\x10\x00\x12\x07\n\x03\x43HF\x10\x01\x12\x07\n\x03\x45UR\x10\x02\x12\x07\n\x03GBP\x10\x03\x12\x07\n\x03USD\x10\x04\x32\xa7\x01\n\x0f\x43urrencyTracker\x12M\n\tsubscribe\x12\x1e.currency_tracker.Subscription\x1a\x1e.currency_tracker.CurrencyData0\x01\x12\x45\n\x0bunsubscribe\x12\x1d.currency_tracker.Cancelation\x1a\x17.currency_tracker.Emptyb\x06proto3')
)

_CURRENCYNAME = _descriptor.EnumDescriptor(
  name='CurrencyName',
  full_name='currency_tracker.CurrencyName',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='AUD', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CHF', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EUR', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GBP', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='USD', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=262,
  serialized_end=321,
)
_sym_db.RegisterEnumDescriptor(_CURRENCYNAME)

CurrencyName = enum_type_wrapper.EnumTypeWrapper(_CURRENCYNAME)
AUD = 0
CHF = 1
EUR = 2
GBP = 3
USD = 4



_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='currency_tracker.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=51,
)


_CANCELATION = _descriptor.Descriptor(
  name='Cancelation',
  full_name='currency_tracker.Cancelation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bankName', full_name='currency_tracker.Cancelation.bankName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=84,
)


_CURRENCYDATA = _descriptor.Descriptor(
  name='CurrencyData',
  full_name='currency_tracker.CurrencyData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='currency', full_name='currency_tracker.CurrencyData.currency', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exchange_ratio', full_name='currency_tracker.CurrencyData.exchange_ratio', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=174,
)


_SUBSCRIPTION = _descriptor.Descriptor(
  name='Subscription',
  full_name='currency_tracker.Subscription',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bankName', full_name='currency_tracker.Subscription.bankName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='currencies', full_name='currency_tracker.Subscription.currencies', index=1,
      number=2, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=260,
)

_CURRENCYDATA.fields_by_name['currency'].enum_type = _CURRENCYNAME
_SUBSCRIPTION.fields_by_name['currencies'].enum_type = _CURRENCYNAME
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['Cancelation'] = _CANCELATION
DESCRIPTOR.message_types_by_name['CurrencyData'] = _CURRENCYDATA
DESCRIPTOR.message_types_by_name['Subscription'] = _SUBSCRIPTION
DESCRIPTOR.enum_types_by_name['CurrencyName'] = _CURRENCYNAME
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'currency_tracker_pb2'
  # @@protoc_insertion_point(class_scope:currency_tracker.Empty)
  ))
_sym_db.RegisterMessage(Empty)

Cancelation = _reflection.GeneratedProtocolMessageType('Cancelation', (_message.Message,), dict(
  DESCRIPTOR = _CANCELATION,
  __module__ = 'currency_tracker_pb2'
  # @@protoc_insertion_point(class_scope:currency_tracker.Cancelation)
  ))
_sym_db.RegisterMessage(Cancelation)

CurrencyData = _reflection.GeneratedProtocolMessageType('CurrencyData', (_message.Message,), dict(
  DESCRIPTOR = _CURRENCYDATA,
  __module__ = 'currency_tracker_pb2'
  # @@protoc_insertion_point(class_scope:currency_tracker.CurrencyData)
  ))
_sym_db.RegisterMessage(CurrencyData)

Subscription = _reflection.GeneratedProtocolMessageType('Subscription', (_message.Message,), dict(
  DESCRIPTOR = _SUBSCRIPTION,
  __module__ = 'currency_tracker_pb2'
  # @@protoc_insertion_point(class_scope:currency_tracker.Subscription)
  ))
_sym_db.RegisterMessage(Subscription)



_CURRENCYTRACKER = _descriptor.ServiceDescriptor(
  name='CurrencyTracker',
  full_name='currency_tracker.CurrencyTracker',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=324,
  serialized_end=491,
  methods=[
  _descriptor.MethodDescriptor(
    name='subscribe',
    full_name='currency_tracker.CurrencyTracker.subscribe',
    index=0,
    containing_service=None,
    input_type=_SUBSCRIPTION,
    output_type=_CURRENCYDATA,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='unsubscribe',
    full_name='currency_tracker.CurrencyTracker.unsubscribe',
    index=1,
    containing_service=None,
    input_type=_CANCELATION,
    output_type=_EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CURRENCYTRACKER)

DESCRIPTOR.services_by_name['CurrencyTracker'] = _CURRENCYTRACKER

# @@protoc_insertion_point(module_scope)
