# -*- coding: utf-8 -*-
#
# Copyright (c) ZeroC, Inc. All rights reserved.
#
#
# Ice version 3.7.2
#
# <auto-generated>
#
# Generated from file `Bank.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

from sys import version_info as _version_info_
import Ice, IcePy

# Start of module Bank
_M_Bank = Ice.openModule('Bank')
__name__ = 'Bank'

if 'InvalidCredentials' not in _M_Bank.__dict__:
    _M_Bank.InvalidCredentials = Ice.createTempClass()
    class InvalidCredentials(Ice.UserException):
        def __init__(self):
            pass

        def __str__(self):
            return IcePy.stringifyException(self)

        __repr__ = __str__

        _ice_id = '::Bank::InvalidCredentials'

    _M_Bank._t_InvalidCredentials = IcePy.defineException('::Bank::InvalidCredentials', InvalidCredentials, (), False, None, ())
    InvalidCredentials._ice_type = _M_Bank._t_InvalidCredentials

    _M_Bank.InvalidCredentials = InvalidCredentials
    del InvalidCredentials

if 'LoanRejectionError' not in _M_Bank.__dict__:
    _M_Bank.LoanRejectionError = Ice.createTempClass()
    class LoanRejectionError(Ice.UserException):
        def __init__(self, reason=''):
            self.reason = reason

        def __str__(self):
            return IcePy.stringifyException(self)

        __repr__ = __str__

        _ice_id = '::Bank::LoanRejectionError'

    _M_Bank._t_LoanRejectionError = IcePy.defineException('::Bank::LoanRejectionError', LoanRejectionError, (), False, None, (('reason', (), IcePy._t_string, False, 0),))
    LoanRejectionError._ice_type = _M_Bank._t_LoanRejectionError

    _M_Bank.LoanRejectionError = LoanRejectionError
    del LoanRejectionError

if 'RegistrationError' not in _M_Bank.__dict__:
    _M_Bank.RegistrationError = Ice.createTempClass()
    class RegistrationError(Ice.UserException):
        def __init__(self, reason=''):
            self.reason = reason

        def __str__(self):
            return IcePy.stringifyException(self)

        __repr__ = __str__

        _ice_id = '::Bank::RegistrationError'

    _M_Bank._t_RegistrationError = IcePy.defineException('::Bank::RegistrationError', RegistrationError, (), False, None, (('reason', (), IcePy._t_string, False, 0),))
    RegistrationError._ice_type = _M_Bank._t_RegistrationError

    _M_Bank.RegistrationError = RegistrationError
    del RegistrationError

if 'UnauthorizedError' not in _M_Bank.__dict__:
    _M_Bank.UnauthorizedError = Ice.createTempClass()
    class UnauthorizedError(Ice.UserException):
        def __init__(self):
            pass

        def __str__(self):
            return IcePy.stringifyException(self)

        __repr__ = __str__

        _ice_id = '::Bank::UnauthorizedError'

    _M_Bank._t_UnauthorizedError = IcePy.defineException('::Bank::UnauthorizedError', UnauthorizedError, (), False, None, ())
    UnauthorizedError._ice_type = _M_Bank._t_UnauthorizedError

    _M_Bank.UnauthorizedError = UnauthorizedError
    del UnauthorizedError

if 'UserAlreadyExistsError' not in _M_Bank.__dict__:
    _M_Bank.UserAlreadyExistsError = Ice.createTempClass()
    class UserAlreadyExistsError(Ice.UserException):
        def __init__(self):
            pass

        def __str__(self):
            return IcePy.stringifyException(self)

        __repr__ = __str__

        _ice_id = '::Bank::UserAlreadyExistsError'

    _M_Bank._t_UserAlreadyExistsError = IcePy.defineException('::Bank::UserAlreadyExistsError', UserAlreadyExistsError, (), False, None, ())
    UserAlreadyExistsError._ice_type = _M_Bank._t_UserAlreadyExistsError

    _M_Bank.UserAlreadyExistsError = UserAlreadyExistsError
    del UserAlreadyExistsError

if 'AccountType' not in _M_Bank.__dict__:
    _M_Bank.AccountType = Ice.createTempClass()
    class AccountType(Ice.EnumBase):

        def __init__(self, _n, _v):
            Ice.EnumBase.__init__(self, _n, _v)

        def valueOf(self, _n):
            if _n in self._enumerators:
                return self._enumerators[_n]
            return None
        valueOf = classmethod(valueOf)

    AccountType.PREMIUM = AccountType("PREMIUM", 0)
    AccountType.STANDARD = AccountType("STANDARD", 1)
    AccountType._enumerators = { 0:AccountType.PREMIUM, 1:AccountType.STANDARD }

    _M_Bank._t_AccountType = IcePy.defineEnum('::Bank::AccountType', AccountType, (), AccountType._enumerators)

    _M_Bank.AccountType = AccountType
    del AccountType

if 'Currency' not in _M_Bank.__dict__:
    _M_Bank.Currency = Ice.createTempClass()
    class Currency(Ice.EnumBase):

        def __init__(self, _n, _v):
            Ice.EnumBase.__init__(self, _n, _v)

        def valueOf(self, _n):
            if _n in self._enumerators:
                return self._enumerators[_n]
            return None
        valueOf = classmethod(valueOf)

    Currency.AUD = Currency("AUD", 0)
    Currency.CHF = Currency("CHF", 1)
    Currency.EUR = Currency("EUR", 2)
    Currency.GBP = Currency("GBP", 3)
    Currency.USD = Currency("USD", 4)
    Currency.PLN = Currency("PLN", 5)
    Currency._enumerators = { 0:Currency.AUD, 1:Currency.CHF, 2:Currency.EUR, 3:Currency.GBP, 4:Currency.USD, 5:Currency.PLN }

    _M_Bank._t_Currency = IcePy.defineEnum('::Bank::Currency', Currency, (), Currency._enumerators)

    _M_Bank.Currency = Currency
    del Currency

if 'LoanOffer' not in _M_Bank.__dict__:
    _M_Bank.LoanOffer = Ice.createTempClass()
    class LoanOffer(object):
        def __init__(self, currency='', amountInPLN=0.0, amount=0.0):
            self.currency = currency
            self.amountInPLN = amountInPLN
            self.amount = amount

        def __eq__(self, other):
            if other is None:
                return False
            elif not isinstance(other, _M_Bank.LoanOffer):
                return NotImplemented
            else:
                if self.currency != other.currency:
                    return False
                if self.amountInPLN != other.amountInPLN:
                    return False
                if self.amount != other.amount:
                    return False
                return True

        def __ne__(self, other):
            return not self.__eq__(other)

        def __str__(self):
            return IcePy.stringify(self, _M_Bank._t_LoanOffer)

        __repr__ = __str__

    _M_Bank._t_LoanOffer = IcePy.defineStruct('::Bank::LoanOffer', LoanOffer, (), (
        ('currency', (), IcePy._t_string),
        ('amountInPLN', (), IcePy._t_double),
        ('amount', (), IcePy._t_double)
    ))

    _M_Bank.LoanOffer = LoanOffer
    del LoanOffer

if 'AccountInfo' not in _M_Bank.__dict__:
    _M_Bank.AccountInfo = Ice.createTempClass()
    class AccountInfo(object):
        def __init__(self, firstName='', lastName='', amount=0.0, type=_M_Bank.AccountType.PREMIUM):
            self.firstName = firstName
            self.lastName = lastName
            self.amount = amount
            self.type = type

        def __eq__(self, other):
            if other is None:
                return False
            elif not isinstance(other, _M_Bank.AccountInfo):
                return NotImplemented
            else:
                if self.firstName != other.firstName:
                    return False
                if self.lastName != other.lastName:
                    return False
                if self.amount != other.amount:
                    return False
                if self.type != other.type:
                    return False
                return True

        def __ne__(self, other):
            return not self.__eq__(other)

        def __str__(self):
            return IcePy.stringify(self, _M_Bank._t_AccountInfo)

        __repr__ = __str__

    _M_Bank._t_AccountInfo = IcePy.defineStruct('::Bank::AccountInfo', AccountInfo, (), (
        ('firstName', (), IcePy._t_string),
        ('lastName', (), IcePy._t_string),
        ('amount', (), IcePy._t_double),
        ('type', (), _M_Bank._t_AccountType)
    ))

    _M_Bank.AccountInfo = AccountInfo
    del AccountInfo

if 'UserCredentials' not in _M_Bank.__dict__:
    _M_Bank.UserCredentials = Ice.createTempClass()
    class UserCredentials(object):
        def __init__(self, pesel='', password=''):
            self.pesel = pesel
            self.password = password

        def __hash__(self):
            _h = 0
            _h = 5 * _h + Ice.getHash(self.pesel)
            _h = 5 * _h + Ice.getHash(self.password)
            return _h % 0x7fffffff

        def __compare(self, other):
            if other is None:
                return 1
            elif not isinstance(other, _M_Bank.UserCredentials):
                return NotImplemented
            else:
                if self.pesel is None or other.pesel is None:
                    if self.pesel != other.pesel:
                        return (-1 if self.pesel is None else 1)
                else:
                    if self.pesel < other.pesel:
                        return -1
                    elif self.pesel > other.pesel:
                        return 1
                if self.password is None or other.password is None:
                    if self.password != other.password:
                        return (-1 if self.password is None else 1)
                else:
                    if self.password < other.password:
                        return -1
                    elif self.password > other.password:
                        return 1
                return 0

        def __lt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r < 0

        def __le__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r <= 0

        def __gt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r > 0

        def __ge__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r >= 0

        def __eq__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r == 0

        def __ne__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r != 0

        def __str__(self):
            return IcePy.stringify(self, _M_Bank._t_UserCredentials)

        __repr__ = __str__

    _M_Bank._t_UserCredentials = IcePy.defineStruct('::Bank::UserCredentials', UserCredentials, (), (
        ('pesel', (), IcePy._t_string),
        ('password', (), IcePy._t_string)
    ))

    _M_Bank.UserCredentials = UserCredentials
    del UserCredentials

_M_Bank._t_Account = IcePy.defineValue('::Bank::Account', Ice.Value, -1, (), False, True, None, ())

if 'AccountPrx' not in _M_Bank.__dict__:
    _M_Bank.AccountPrx = Ice.createTempClass()
    class AccountPrx(Ice.ObjectPrx):

        def getCurrentState(self, credentials, context=None):
            return _M_Bank.Account._op_getCurrentState.invoke(self, ((credentials, ), context))

        def getCurrentStateAsync(self, credentials, context=None):
            return _M_Bank.Account._op_getCurrentState.invokeAsync(self, ((credentials, ), context))

        def begin_getCurrentState(self, credentials, _response=None, _ex=None, _sent=None, context=None):
            return _M_Bank.Account._op_getCurrentState.begin(self, ((credentials, ), _response, _ex, _sent, context))

        def end_getCurrentState(self, _r):
            return _M_Bank.Account._op_getCurrentState.end(self, _r)

        @staticmethod
        def checkedCast(proxy, facetOrContext=None, context=None):
            return _M_Bank.AccountPrx.ice_checkedCast(proxy, '::Bank::Account', facetOrContext, context)

        @staticmethod
        def uncheckedCast(proxy, facet=None):
            return _M_Bank.AccountPrx.ice_uncheckedCast(proxy, facet)

        @staticmethod
        def ice_staticId():
            return '::Bank::Account'
    _M_Bank._t_AccountPrx = IcePy.defineProxy('::Bank::Account', AccountPrx)

    _M_Bank.AccountPrx = AccountPrx
    del AccountPrx

    _M_Bank.Account = Ice.createTempClass()
    class Account(Ice.Object):

        def ice_ids(self, current=None):
            return ('::Bank::Account', '::Ice::Object')

        def ice_id(self, current=None):
            return '::Bank::Account'

        @staticmethod
        def ice_staticId():
            return '::Bank::Account'

        def getCurrentState(self, credentials, current=None):
            raise NotImplementedError("servant method 'getCurrentState' not implemented")

        def __str__(self):
            return IcePy.stringify(self, _M_Bank._t_AccountDisp)

        __repr__ = __str__

    _M_Bank._t_AccountDisp = IcePy.defineClass('::Bank::Account', Account, (), None, ())
    Account._ice_type = _M_Bank._t_AccountDisp

    Account._op_getCurrentState = IcePy.Operation('getCurrentState', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), _M_Bank._t_UserCredentials, False, 0),), (), ((), _M_Bank._t_AccountInfo, False, 0), (_M_Bank._t_UnauthorizedError,))

    _M_Bank.Account = Account
    del Account

_M_Bank._t_PremiumAccount = IcePy.defineValue('::Bank::PremiumAccount', Ice.Value, -1, (), False, True, None, ())

if 'PremiumAccountPrx' not in _M_Bank.__dict__:
    _M_Bank.PremiumAccountPrx = Ice.createTempClass()
    class PremiumAccountPrx(_M_Bank.AccountPrx):

        def takeALoan(self, credentials, currency, amount, context=None):
            return _M_Bank.PremiumAccount._op_takeALoan.invoke(self, ((credentials, currency, amount), context))

        def takeALoanAsync(self, credentials, currency, amount, context=None):
            return _M_Bank.PremiumAccount._op_takeALoan.invokeAsync(self, ((credentials, currency, amount), context))

        def begin_takeALoan(self, credentials, currency, amount, _response=None, _ex=None, _sent=None, context=None):
            return _M_Bank.PremiumAccount._op_takeALoan.begin(self, ((credentials, currency, amount), _response, _ex, _sent, context))

        def end_takeALoan(self, _r):
            return _M_Bank.PremiumAccount._op_takeALoan.end(self, _r)

        @staticmethod
        def checkedCast(proxy, facetOrContext=None, context=None):
            return _M_Bank.PremiumAccountPrx.ice_checkedCast(proxy, '::Bank::PremiumAccount', facetOrContext, context)

        @staticmethod
        def uncheckedCast(proxy, facet=None):
            return _M_Bank.PremiumAccountPrx.ice_uncheckedCast(proxy, facet)

        @staticmethod
        def ice_staticId():
            return '::Bank::PremiumAccount'
    _M_Bank._t_PremiumAccountPrx = IcePy.defineProxy('::Bank::PremiumAccount', PremiumAccountPrx)

    _M_Bank.PremiumAccountPrx = PremiumAccountPrx
    del PremiumAccountPrx

    _M_Bank.PremiumAccount = Ice.createTempClass()
    class PremiumAccount(_M_Bank.Account):

        def ice_ids(self, current=None):
            return ('::Bank::Account', '::Bank::PremiumAccount', '::Ice::Object')

        def ice_id(self, current=None):
            return '::Bank::PremiumAccount'

        @staticmethod
        def ice_staticId():
            return '::Bank::PremiumAccount'

        def takeALoan(self, credentials, currency, amount, current=None):
            raise NotImplementedError("servant method 'takeALoan' not implemented")

        def __str__(self):
            return IcePy.stringify(self, _M_Bank._t_PremiumAccountDisp)

        __repr__ = __str__

    _M_Bank._t_PremiumAccountDisp = IcePy.defineClass('::Bank::PremiumAccount', PremiumAccount, (), None, (_M_Bank._t_AccountDisp,))
    PremiumAccount._ice_type = _M_Bank._t_PremiumAccountDisp

    PremiumAccount._op_takeALoan = IcePy.Operation('takeALoan', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), _M_Bank._t_UserCredentials, False, 0), ((), IcePy._t_string, False, 0), ((), IcePy._t_double, False, 0)), (), ((), _M_Bank._t_LoanOffer, False, 0), (_M_Bank._t_UnauthorizedError, _M_Bank._t_LoanRejectionError))

    _M_Bank.PremiumAccount = PremiumAccount
    del PremiumAccount

if 'RegistrationResponse' not in _M_Bank.__dict__:
    _M_Bank.RegistrationResponse = Ice.createTempClass()
    class RegistrationResponse(object):
        def __init__(self, password='', accountType=_M_Bank.AccountType.PREMIUM, account=None):
            self.password = password
            self.accountType = accountType
            self.account = account

        def __eq__(self, other):
            if other is None:
                return False
            elif not isinstance(other, _M_Bank.RegistrationResponse):
                return NotImplemented
            else:
                if self.password != other.password:
                    return False
                if self.accountType != other.accountType:
                    return False
                if self.account != other.account:
                    return False
                return True

        def __ne__(self, other):
            return not self.__eq__(other)

        def __str__(self):
            return IcePy.stringify(self, _M_Bank._t_RegistrationResponse)

        __repr__ = __str__

    _M_Bank._t_RegistrationResponse = IcePy.defineStruct('::Bank::RegistrationResponse', RegistrationResponse, (), (
        ('password', (), IcePy._t_string),
        ('accountType', (), _M_Bank._t_AccountType),
        ('account', (), _M_Bank._t_AccountPrx)
    ))

    _M_Bank.RegistrationResponse = RegistrationResponse
    del RegistrationResponse

_M_Bank._t_User = IcePy.defineValue('::Bank::User', Ice.Value, -1, (), False, True, None, ())

if 'UserPrx' not in _M_Bank.__dict__:
    _M_Bank.UserPrx = Ice.createTempClass()
    class UserPrx(Ice.ObjectPrx):

        def registerNewAccount(self, firstName, lastName, pesel, monthlyDeposit, context=None):
            return _M_Bank.User._op_registerNewAccount.invoke(self, ((firstName, lastName, pesel, monthlyDeposit), context))

        def registerNewAccountAsync(self, firstName, lastName, pesel, monthlyDeposit, context=None):
            return _M_Bank.User._op_registerNewAccount.invokeAsync(self, ((firstName, lastName, pesel, monthlyDeposit), context))

        def begin_registerNewAccount(self, firstName, lastName, pesel, monthlyDeposit, _response=None, _ex=None, _sent=None, context=None):
            return _M_Bank.User._op_registerNewAccount.begin(self, ((firstName, lastName, pesel, monthlyDeposit), _response, _ex, _sent, context))

        def end_registerNewAccount(self, _r):
            return _M_Bank.User._op_registerNewAccount.end(self, _r)

        def login(self, credentials, context=None):
            return _M_Bank.User._op_login.invoke(self, ((credentials, ), context))

        def loginAsync(self, credentials, context=None):
            return _M_Bank.User._op_login.invokeAsync(self, ((credentials, ), context))

        def begin_login(self, credentials, _response=None, _ex=None, _sent=None, context=None):
            return _M_Bank.User._op_login.begin(self, ((credentials, ), _response, _ex, _sent, context))

        def end_login(self, _r):
            return _M_Bank.User._op_login.end(self, _r)

        @staticmethod
        def checkedCast(proxy, facetOrContext=None, context=None):
            return _M_Bank.UserPrx.ice_checkedCast(proxy, '::Bank::User', facetOrContext, context)

        @staticmethod
        def uncheckedCast(proxy, facet=None):
            return _M_Bank.UserPrx.ice_uncheckedCast(proxy, facet)

        @staticmethod
        def ice_staticId():
            return '::Bank::User'
    _M_Bank._t_UserPrx = IcePy.defineProxy('::Bank::User', UserPrx)

    _M_Bank.UserPrx = UserPrx
    del UserPrx

    _M_Bank.User = Ice.createTempClass()
    class User(Ice.Object):

        def ice_ids(self, current=None):
            return ('::Bank::User', '::Ice::Object')

        def ice_id(self, current=None):
            return '::Bank::User'

        @staticmethod
        def ice_staticId():
            return '::Bank::User'

        def registerNewAccount(self, firstName, lastName, pesel, monthlyDeposit, current=None):
            raise NotImplementedError("servant method 'registerNewAccount' not implemented")

        def login(self, credentials, current=None):
            raise NotImplementedError("servant method 'login' not implemented")

        def __str__(self):
            return IcePy.stringify(self, _M_Bank._t_UserDisp)

        __repr__ = __str__

    _M_Bank._t_UserDisp = IcePy.defineClass('::Bank::User', User, (), None, ())
    User._ice_type = _M_Bank._t_UserDisp

    User._op_registerNewAccount = IcePy.Operation('registerNewAccount', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0), ((), IcePy._t_int, False, 0)), (), ((), _M_Bank._t_RegistrationResponse, False, 0), (_M_Bank._t_RegistrationError, _M_Bank._t_UserAlreadyExistsError))
    User._op_login = IcePy.Operation('login', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), _M_Bank._t_UserCredentials, False, 0),), (), ((), _M_Bank._t_AccountPrx, False, 0), (_M_Bank._t_UnauthorizedError,))

    _M_Bank.User = User
    del User

# End of module Bank
